version: "3.7"
services:
    server:
        container_name: ng-server
        restart: always
        build:
            context: ./server
            dockerfile: Dockerfile.dev
            target: development
            args:
                NODE_PORT: 3000
        volumes:
            - ./server:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - "3000:3000"
