version: "3.7"
services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
            target: development
        volumes:
            - ./frontend:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - "5173:5173"
        stdin_open: true
    server:
        container_name: ng-server
        build:
            context: ./server
            dockerfile: Dockerfile.dev
            target: development
            args:
                NODE_PORT: 3000
        volumes:
            - ./server:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - "3000:3000"
