version: "3.7"
services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
            target: development
        volumes:
            - ./frontend/:/home/node/app/
            - /home/node/app/node_modules
        ports:
            - "5173:5173"
    server:
        restart: always
        build:
            context: ./server
            dockerfile: Dockerfile.dev
            target: development
        environment:
            - PORT=3000
        volumes:
            - ./server:/home/node/app
            - /home/node/app/node_modules
        ports:
            - "3000:3000"
