FROM node:lts-alpine AS development

ENV NODE_ENV development

ARG NODE_PORT

RUN echo "Argument port is: $NODE_PORT"

WORKDIR /usr/server

COPY ./package*.json /usr/server
RUN npm i

COPY . .

EXPOSE ${NODE_PORT}

CMD [ "node", "run", "dev" ]
