FROM node:lts-alpine AS development

ENV NODE_ENV development

ARG NODE_PORT

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

WORKDIR /home/node/app

COPY --chown=node:node ./package*.json ./

USER node

RUN npm install

COPY --chown=node:node . .

EXPOSE ${NODE_PORT}

CMD [ "npm", "run", "dev" ]
